version: '3.5'

services:
  next:
    build:
      dockerfile: .docker/dev.Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - 'pnpm-store:/pnpm/store/v3'
    networks:
      - next
  mysql:
    image: 'mysql:8.0'
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - 'next-mysql:/var/lib/mysql'
    networks:
      - next
  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin:latest'
    environment:
      PMA_HOST: 'mysql'
      PMA_USER: 'root'
      PMA_PASSWORD: 'password'
    ports:
      - '8080:80'
    networks:
      - next
    depends_on:
      - mysql

networks:
  next:
    driver: bridge

volumes:
  pnpm-store:
    driver: local
  next-mysql:
    driver: local
